C/Absolute number progam.c
C/C program to print the sum of odd numbers.c

This code is to print the sum of the odd numbers specified.

I contributed

---

README.md

Fixed the documentation a bit and fixed a few grammatical errors!

Updated the readme and fixed a few grammatical errors

---

Python/Design_Patterns_Builder_and_Proxy/Builder Design Pattern.py
Python/Design_Patterns_Builder_and_Proxy/Output.md
Python/Design_Patterns_Builder_and_Proxy/Proxy Design Pattern.py
README.md

Contributors and Design patterns folder added

Design Patterns added

---

C#/Fibonacci Series.cs
C#/Number to Word Converter.cs
C#/Palindrome Checker.cs
C#/ReadMe.md
README.md

Number converter to words program

---

C#/MomentoPattern.cs
C#/StrategyPattern.cs

Added C# code for "Strategy" and "Momento" Design Patterns

Two design Patterns Added

---

JavaScript/Todo list/index.html
JavaScript/Todo list/js/app.js
JavaScript/Todo list/scss/index.css

Mark your task as done when it's completed. Or undo it.

Set the task completion status feature added

---

README.md

I'm adding a link to CONTRIBUTION.md, just so it becomes more convenient to access. Thanks

adding a link to CONTRIBUTION.md

---

Python/tictactoe.py

TicTacToe game Created

---

Java/floydsTriangle.java
Java/hollowRec.java
README.md

would you mind adding me to the contributors list in the mainpage of this code, thanks.

Added JAVA files and updated README file

---

C++/hashing.cpp

Added a cpp file that contains hashing code. It takes input from user and store the input in array using hashing alogs

Added Hashing algo

---

C#/hangman.cs

This is a C# Program to create a HangMan game.

HangMan C Sharp

---

Python/Grocery_Store_Management_Project.py
Python/Read Me First.txt
Python/all_items.txt

I am adding Grocery Store Management Software

Grocery Store Management Software

---

Java/Odd&EvenSort.java

java file for even and odd sorting is added in this commit

Odd and even sorting code is added

---

C/tower-of-hanoi.c

Added C Program to solve Tower of Hanoi Problem

Added Tower of Hanoi C Program

---

C/bubble-sort.c

Added C Program to sort numbers using Bubble Sort Algorithm

Added Bubble Sort C Program

---

Python/linklist.py

please accept my PR for hacktoberfest

Added linked list implementation in python

---

C++/Expression-Evaluation.cpp

Expression evaluation using C++ Stack

Expression Evaluation

---

C++/PalindromeCheck.cpp

Expression Palindrome Check using C++ Stack

Palindrome Check

---

C++/PrefixSums1d.cpp
C++/prefixSums2d.cpp
Java/PrefixSums.java
Python/PrefixSums.py

Have added Prefix sum approach in Java C++ and Python

Diff lang codes for Prefix Sums

---

Python/diagonal-matrix-print.cpp
Python/staicase-searching-2d.cpp

Staircase search and diagonal printing in 2D arrays code

---

Python/portscanner.py

A program that scans for open ports on a given IP address.

Port Scanner

---

C++/15+ Array Operation/Delete item in array.cpp
C++/15+ Array Operation/Find Duplicate.cpp
C++/15+ Array Operation/Find Second largest.cpp
C++/15+ Array Operation/Find Union and Intersection.cpp
C++/15+ Array Operation/Minimum and maximum.cpp
C++/15+ Array Operation/insertion in array.cpp
C++/15+ Array Operation/kth largest.cpp
C++/15+ Array Operation/kth minimum in an array.cpp
C++/15+ Array Operation/largemaxcontigiou sub array.cpp
C++/15+ Array Operation/linear search how to find elemet .cpp
C++/15+ Array Operation/moving neagativ element to one side.cpp
C++/15+ Array Operation/remove ith element .cpp
C++/15+ Array Operation/reverse an array.cpp
C++/15+ Array Operation/rotate an array by one.cpp
C++/15+ Array Operation/sort array.cpp

The 15+ Array base Operation will help us to improve our logic skills, and most importantly the basics of Data Structure and algorithm in C++.

15+ Array operations

---

README.md

Hey, i have noticed that there is mistake in layout of table and I corrected it.

Corrected layout of README 

---

C++/Merge_sort.cpp
C++/Quick_sort.cpp

Hey I have added the code of quick and merge sort in c++.
Pls review it.
Resolve #145

Added quick and merge sort in c++

---

Python/hangman.py
Python/helloworld.py

I have made some changes in the python code.

first ever commit

---

Python/reverse_no_generator.py

I have added reverse number generator pattern build in Python language. This branch is able to merge. Kindly accept the PR, Cheers! :D

Add reverse_no_generator.py

---

C#/SingletonPattern.cs

In a Single pattern, the class doesn't allow more than one instance. It is useful for storing data in one place.

Added the Singleton Pattern in C#

---

C++/Bitonic_Sort.cpp
C++/Shell_sort.cpp

Adding Shell_sort and Bitonic_sort Python

Adding Shell_sort and Bitonic_sort Python

---

Python/quiz_game.py

A quiz game

---

C/matrix_addition.c
Python/bitcoin.py

1) Added matrix_additon program in C.
2) Added bitcoin.py a bitcoin price index program that displays the current market price of the number of bitcoin user who wants to buy using API.

Created bitcoin.py and matrix_additon.c

---

Python/black-jack.py
README.md

black-jack Game

---

Python/7_List_Comprehensions.py

List Comprehensions (Solved HackerRank Problem)

List Comprehensions

---

JavaScript/TodoApp/index.css
JavaScript/TodoApp/index.html
JavaScript/TodoApp/index.js

This is a To Do App by using html css and javaScript. I used local storage to store tasks to do and task that has been completed. There are also option to create a task complete a task and delete tasks.

Added To Do App develop in JS using local Storage

---

C++/Stack Implementation.cpp
C++/Stack Sort.cpp
C++/Tower oh Hannio.cpp

Stack Implementation

---

C++/STL/List.cpp

Hello,
I have added code for C++ STL container list in the repo by following all the guidelines. Please accept this Pull request.
For this, I will be grateful to you.
Thank you.

Added List.cpp

---

C++/guessing_game.cpp

Guessing game to guess random numbers selected by the host.

guessing game

---

Java/ButterflyPattern

This code first asks the user to input the size of butterfly, then prints the butterfly pattern

ButterflyPattern.java

---

C++/InterpolationSearch.cpp

Interpolation search is an improved version of binary search. This search algorithm works on the finding position of the required value. For proper working of this algorithm, the data collection should be in a sorted form and equally distributed.

Interpolation Search added to C++ Directory

---

Python/compute_total_score.py

Test Gorilla interview question entry-level problem using python
An array of integers, compute a total score based on the following rules: 
1. Add 1 point for every even number in the array 
2. Add 3 points for every odd number in the array 
3. 3. Add 5 points for every time you encounter an 8 in the array 
Examples: 
Input: my_numbers-[1,2,3,4,5) Output: 11 
Input: my_numbers=(15,25,35] Output: 9 
Input: my_numbers=[8,8] Output: 10

compute total score

---

Java/Fraction

This JAVA class is used to manipulate Fractions. We can add, subtract, multiply, divide, simplify fractions.

Fraction.java

---

C++/GoF Patterns/Abstract Factory Pattern/Abstract_Factory.cpp
C++/GoF Patterns/Adapter Pattern/Source.cpp
C++/GoF Patterns/FASAD Pattern/Source.cpp
C++/GoF Patterns/Factory Pattern/Source.cpp
C++/GoF Patterns/Singleton Pattern/Singelton.cpp
JavaScript/Shut the Box/Task02_Function.js
JavaScript/Shut the Box/Task02_Style.css
JavaScript/Shut the Box/index.html

Gang of four patterns are the best practices that are followed during the development of a system

Gang of Four Patterns added to C++

---

Element Class

Element Class

---

Rock_paper_scissor.py

This is a game where a player select the one of the mentioned and the computer will select one off the mentioned and a message will be appeared pointing out the winner.

rock_paper_scissor.py

---

C/sparse_matrix_addition.c

sparse matrix addition problem in c.

added sparse matrix addition

---

card_game.py

This is a randomly generated card game that shows the winner depending upon certain conditions.

card_game.py

---

sum_of_pair.py

This is program for the sum of pairs in which a list is given and a number is selected whose pair sum will be returned and shown on the screen.

sum_of_pairs.py

---

Fronend-Projects/Foodie/menu.html

i have updated a little bit in front end foodie menu.

foodie-menu updated

---

C++/BattleshipGame/BattleShip.cpp
C++/BattleshipGame/BattleShip.h
C++/BattleshipGame/Carrier.cpp
C++/BattleshipGame/Carrier.h
C++/BattleshipGame/Destroyer.cpp
C++/BattleshipGame/Destroyer.h
C++/BattleshipGame/GameEngine.cpp
C++/BattleshipGame/PTBoat.cpp
C++/BattleshipGame/PTBoat.h
C++/BattleshipGame/Player.cpp
C++/BattleshipGame/Player.h
C++/BattleshipGame/Ship.cpp
C++/BattleshipGame/Ship.h
C++/BattleshipGame/Submarine.cpp
C++/BattleshipGame/Submarine.h
C++/BattleshipGame/Type.h

A Battleship game made with pure logic using cpp.

Added Battleship Game

---

C++/Decimal To Octal Conversion.cpp

This program converts a decimal number to Octal in C++.

Decimal To Octal Conversion

---

C++/factorial.cpp

this code find factorial of positive number

Factorial_of_given_Number

---

JavaScript/EvenOrOdd.html

Script to check if number is even or odd

Check if a number is even or odd

---

arrange name in alphabatical order.cpp

This program arrange names in alphabatical order

arrange name in alphabatical order.cpp

---

backtrackingcpp.cpp

By Bit manipulation,Generate all possible subset of set

Generate all possible subset of set

---

C++/lapindrome.cpp

This progam checks whether a string is lapindrome or not.

Lapindrome in C++

---

Sum Of Left Diagonal.cpp

This program is to find the sum of Left Diagonal Matrix.

Sum of Left Diagonal

---

C++/Two_Array_Equal_Or_Not.cpp

Given two arrays, arr1 and arr2 of equal length N, the task is to find if the given arrays are equal or not. 
Two arrays are said to be equal if:
both of them contain the same set of elements, 
arrangements (or permutations) of elements might/might not be same. If there are repetitions, then counts of repeated elements must also be the same for two arrays to be equal.

Two Array are Equal or Not

---

Bank_accout.cpp
hcf.cpp

This code is used to manage the Bank account of customer

Management of Bank account

---

C++/college cafe.cpp
C++/employ management.cpp
PHP/email.php

simple small c++ management projects

managements project

---

Reverse.cpp
back.cpp

by Bit manipulation,check number is the power of 2

check number power of 2

---

C/Replace_EveryElement_With_least_GreaterElement_on_Its_Right.c

Given an Array ,Replace every element in that array with the greatest element among the elements to its right, and replace the last element with -1.

Replace Elements With Least Greater On Its Right

---

Lab.cpp

Number of Objects created in Memory using concept of constructors, destructors, classes &  static variables.

Number of objects created in memory

---

C++/15+ Array Operation/Leader Elements in 1D Array.cpp

An element is leader if it is greater than all the elements to its right side. The rightmost element is always a leader.

Leader Elements in 1D Array

---

C++/Neon number.cpp

A neon number is a number in which the sum of digits of the square of the number is equal to the number itself.

Neon number

---

C++/symmetric matrix.cpp

check whether a matrix is symmetric or not .

Symmetric matrix

---

C++/butterfly pattern.cpp

this is the c++ pattern which prints the butterfly

butterfly pattern

---

C++/Return integer from string.cpp

This program extract an integer from a string.

Return integer from a string

---

C++/Project1.sln

this project contain program of swapping without using 3rd variable

swapping without 3rd variable

---

Median Function.cpp

This program finds median of entered numbers. Thank you!

Median of entered numbers (using Arrays concept)

---

C++/tictacto - 2.cpp
maggic square.cpp

This is a 3x3 magic square game that makes different values

Magic Square 3X3

---

Revers_Words_In_String.cpp

This Program Will Reverse the Whole Sentence in the Same Order.

Reverse Words in String

---

C++/array rezise

resizing array and populating it with double the value of initial data.

Create resized array

---

C++/operator overload

overloading + operator for 2 objects of a class.

Create operator overload

---

C++/copy constructor

default and copy constructor of a class.

Create copy constructor

---

C++/gcd and simplification

finding gcd and simplification of a fraction ( class object )

Create gcd and simplification

---

Input a Series.py
Magic Date.py
Restaurant slip.py
Stadium Seats Profit.py

ADVANCED PROGRAM

---

C++/image_histogram.cpp

The histogram is a graph showing the number of pixels in an image at each different intensity value found in an image.

image_histogram.cpp

---

C++/Fast Solution of 3 Problems/RemoveDuplicates.cpp
C++/Fast Solution of 3 Problems/ReverseNumber.cpp
C++/Fast Solution of 3 Problems/TwoSum.cpp
README.md

I am adding faster solutions to the problems of leetcode.

Osmcpu problems

---

C++/Lowest Common Ancestor of Binary Tree/tree.cpp

Q: Lowest Common Ancestor in a Binary Tree
Given a Binary Tree with all unique values and two nodes value, n1 and n2. The task is to find the lowest common ancestor of the given two nodes. We may assume that either both n1 and n2 are present in the tree or none of them are present.
LCA: It is the first common ancestor of both the nodes n1 and n2 from bottom of tree.
Solution of the above is done in CPP in the CPP folder, in folder titled: "Lowest Common Ancestor of Binary Tree"

ft. added a CPP Tree solution

---

C++/Max Sum of non-adjacent nodes/maxsumtree.cpp

Please merge this under the hacktoberfest lable. Thanks!

ft. added a medium level TREE qna in CPP

---

C#/BlogsApplication.cs

This file contains repository code for a blog application.

Blogs Application Code

---

C++/Bubble_Sort.cpp
C++/Factorial.cpp
C++/Reverse.cpp
C++/binarySearch.cpp
PHP/Web-Scrapper/Php and Database Connection.php
PHP/Web-Scrapper/crawl.php
PHP/Web-Scrapper/crawler.sql
Python/LCM.py

This web scrapper is developed in core PHP with a user-friendly GUI. 
Allows to scrap:
- Website
- Title
- Description
- Internal Links

Web Scrapper

---

C++/Longest Max Sum Bloodline of Binary Tree/LongestBloodline.cpp

Q:Given a binary tree of size N. Your task is to complete the function sumOfLongRootToLeafPath(), that find the sum of all nodes on the longest path from root to leaf node. If two or more paths compete for the longest path, then the path having maximum sum of nodes is being considered.
I've given the solution to the following problem in the CPP folder in a folder titled: Longest Max Sum Bloodline of Binary Tree

added a famous Medium level Tree qna in CPP

---

Java/BarCharts.java

This code of java constructs bar charts (vertical or horizontal).

Bar Charts Java Code

---

Java/tower_of_hanoi.java

A program to solve Tower of Hanoi using stack in java.

tower_of_hanoi.java

---

Python/CurrencyConverter/admin.py
Python/CurrencyConverter/currency.py
Python/CurrencyConverter/currency.sql
Python/CurrencyConverter/insert.py
Python/CurrencyConverter/main.py
Python/CurrencyConverter/mysqlconnect.py

Currency converter made in python by using MYSQL as database.

Added Currency converter in python by using MYSQL

---

swapingsid.js

swaping without using 3rd veriable

---

Python/yt_downloader.py

Download any youtube video using Python.
Run the program via
```
$ cd Python
python yt_downloader.py --url  https://www.youtube.com/watch\?v\=f-xGecL2H2w\&ab_channel\=DeepLearningAI
```
Install pytube first
```
$ pip install pytube
```

Download any Youtube video by providing url

---

Python/Hill-Cipher-Algorithm.py

Adding a Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.

Adding a Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.

---

C#/Swap.cs
README.md

Added program two swap two numbers.

Added C# Program

---

to find largest and smallest.c

i have added a file to find largest and smallest number using c

added a file to find largest and smallest number using c

---

Python/Pattern with recursion in python.py

I have added a file a file that prints a triangle with recursion in python by taking number of rows from the user.

Triangle pattern with recursion in python

---

C++/Stack in linked list.cpp

Create Stack in linked list.cpp

---

Python/Power function with recursion in python.py
Python/multiply 2 numbers with recursion.py

I have added a file that takes two numbers as input and prints thier product using recursion in python.

Multiply two numbers with recursion in python

---

Java/Floyd’s_triangle.java

Floyd’s triangle is a triangle with first natural numbers. It is the right arrangement of the numbers/values or patterns. Basically, it is a left to right arrangement of natural numbers in a right-angled triangle

added Floyds Triangle Pattern

---

C++/Coin_Change_Problem.cpp

The idea is to use recursion to solve this problem. We recur to see if the total can be reached by choosing the coin or not for each coin of given denominations. If choosing the current coin results in the solution, update the total number of ways.

added coin change problem

---

C++/Subset_Sum_Problem.cpp

A naive solution would be to cycle through all subsets of n numbers and, for every one of them, check if the subset sums to the right number. The running time is of order O(2n.n) since there are 2n subsets, and to check each subset, we need to sum at most n elements.

added Subset Sum Problem in C++

---

Python/sum of non neg list elements with recursion in python.py

I have added a file that contains recursive function to print the sum of the non-negative list elements.I have taken list by filling it using random module.However, it will work same with any list.

sum of non-negative list elements using recursive function in python

---

PHP/Crud Operations in PHP/Php and Database Connection.php
PHP/Crud Operations in PHP/README.md
PHP/Crud Operations in PHP/delete.php
PHP/Crud Operations in PHP/edit.php
PHP/Crud Operations in PHP/index.php
PHP/Crud Operations in PHP/insert.php
PHP/Crud Operations in PHP/web_programming.sql

This project covers working of CRUD (Create, Read, Update, Delete) Operations in depth with PHP.

Crud Operations in PHP

---

DataScienceandML/Kaggle Titanic.ipynb

I have added a python notebook that predicts the titanic survivor rate using Logistic Regression

Titanic Survivor Prediction

---

C++/Patternprogram/pattern 1.cpp
C++/Patternprogram/pattern 2.cpp
C++/Patternprogram/pattern 3 (number pyramid).cpp
C++/Patternprogram/pattern 4.cpp
C++/Patternprogram/pattern 5.cpp
C++/decimaltobinaryhexaoctfunc.cpp

added decimal to octal hexadecimal and binary functions and 5 pattern programs in cpp

added 5 pattern programs and decimal conversion functions

---

HammingCode.java
checksum_sender.java

Implemented Hamming Code using java

Implemeneted Hamming Code

---

C++/Tree/BinaryTree.cpp

I have implemented all the basic and intremiediate functions and operations done on binary tree.

All function of Binary Tree

---

Python/shuffle_cards.py

Python Program to Shuffle Deck of Cards 
o/p-
You got:
5 of Heart
1 of Heart
8 of Spade
12 of Spade
4 of Spade

Created Python Program to Shuffle Deck of Cards

---

Problems/factorial of a number.py

I have added function of factorial of a number.

added factorial of a number

---

C++/Graph/BFS_traverse.cpp

Here is the source code of the C++ program to display the breadth first method of traversing nodes in a graph along with a display of the start and end time of a visited node. This C++ program is successfully compiled and run on DevCpp, a C++ compiler. The program output is given below.

C++ Program to Traverse a Graph using BFS
